/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.hoadon.HoaDon;
import model.hoadon.hoaDonChiTiet;
import model.sanpham.ChiTietSanPham;
import model.sanpham.SanPham;
import service.HoaDonService;
import service.ISanPhamSevice;
import service.impl.HoaDonServiceIpml;
import service.impl.SanPHamSeviceImpl;
import viewmodel.ChiTietSPCustom;
import viewmodel.HoaDonCustom2;
import viewmodel.SanPhamCustom;

/**
 *
 * @author asus_vinh
 */
public class HoaDonQuanLyForm extends javax.swing.JFrame {
private List<HoaDonCustom2>listHoaDon = new ArrayList();
private DefaultTableModel dtm = new DefaultTableModel();
private HoaDonService service = new HoaDonServiceIpml();
private List<HoaDonCustom2>listHoaDonHuy = new ArrayList();
private List<HoaDonCustom2>listHoaDonThanhToan = new ArrayList();
private List<HoaDonCustom2>listHoaDonGiao = new ArrayList();
private List<SanPhamCustom>listSanPham = new ArrayList<>();
private List<ChiTietSPCustom>listChiTietSP = new ArrayList<>();
private ISanPhamSevice sanPhamService = new SanPHamSeviceImpl();
private DefaultComboBoxModel dcm = new DefaultComboBoxModel();
private DefaultComboBoxModel dcm2 = new DefaultComboBoxModel();
    /**
     * Creates new form NewJFrame
     */
    public HoaDonQuanLyForm() {
        initComponents();
        table.setModel(dtm);
        String []headers = {"Mã HD","Tên SP","Ngày tạo","Ngày TT","Ngày Ship","Ngày nhận","Tên người nhận","Địa chỉ","SDT","Số lượng","Đơn giá","Tình trạng"};
        dtm.setColumnIdentifiers(headers);
        listSanPham = sanPhamService.getAllSanPham();
        tenSP.setModel(dcm);
        for(SanPhamCustom sp : listSanPham){
            dcm.addElement(sp.getTen());
        }
        tenSP.setSelectedIndex(0);
        listChiTietSP = sanPhamService.getAll();
        listHoaDon=service.getAllHoaDon();
        duyetTinhTrang(listHoaDon);
        loadTinhTrang();
        
        
    }
    
    
    private void loadTinhTrang(){
        if(trangThai.getSelectedIndex()==0){
            loadTable(listHoaDonHuy);
        }
        else if(trangThai.getSelectedIndex()==1){
            loadTable(listHoaDonThanhToan);
        }
        else if(trangThai.getSelectedIndex()==2){
            loadTable(listHoaDonGiao);
        }
    }
            
    private String setTinhTrang(List<HoaDonCustom2>list){
        String tinhTrang ="";
        for(HoaDonCustom2 hd : list){
            if(hd.getTrangThai()==0){
                tinhTrang = "Đã hủy";
            }
            else if(hd.getTrangThai()==1){
                tinhTrang = "Đã thanh toán";
            }
            else if(hd.getTrangThai()==2){
                tinhTrang =  "Đang giao";
            }
        }
        return tinhTrang;
    }
    
    private void duyetTinhTrang(List<HoaDonCustom2>list){
        for(HoaDonCustom2 hd : list){
            listHoaDonHuy.remove(hd);
            listHoaDonGiao.remove(hd);
            listHoaDonThanhToan.remove(hd);
        }
        for(HoaDonCustom2 hd : list){
            if(null!=hd.getTrangThai())switch (hd.getTrangThai()) {
                case 0:
                    listHoaDonHuy.add(hd);
                    break;
                case 1:
                    listHoaDonThanhToan.add(hd);
                    
                    break;
                case 2:
                    listHoaDonGiao.add(hd);
                    
                    break;
                default:
                    break;
            }
            
        }
    }
    

            
    private void loadTable(List<HoaDonCustom2>list){
        dtm.setRowCount(0);
        for(HoaDonCustom2 hd : list){
            dtm.addRow(new Object[]{
                hd.getMa(),hd.getTenSP(),hd.getNgayTao(),hd.getNgayThanhToan(),hd.getNgayShip(),hd.getNgayNhan(),hd.getTenNguoiNhan(),hd.getDiaChi(),hd.getSdt(),hd.getSoLuong(),hd.getDongia(),setTinhTrang(list)
            });
        } 
    }
    
    private int getIdCTSP(String tenSP){
        int idSP=10000;
        for(ChiTietSPCustom ctsp : listChiTietSP){
            if(ctsp.getTenSP().equals(tenSP)){
                idSP=ctsp.getId();
            }
        }
        return idSP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtNgaynhan = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNgayShip = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        radioDaThanhToan = new javax.swing.JRadioButton();
        radioHuy = new javax.swing.JRadioButton();
        radioDangGiao = new javax.swing.JRadioButton();
        jLabel41 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtSodienThoai = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtTenNguoiNhan = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtNgayThanhToan = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        trangThai = new javax.swing.JComboBox<>();
        tenSP = new javax.swing.JComboBox<>();
        check = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Danh sách hóa đơn");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Mã HD:");

        txtMaHD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 0, 0)));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Tên SP:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Ngày Nhận:");

        txtNgaynhan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 0, 0)));

        txtSoLuong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 0, 0)));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Số lượng :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Ngày Ship:");

        txtNgayShip.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Tình trạng:");

        radioDaThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioDaThanhToan);
        radioDaThanhToan.setText("Đã Thanh toán");

        radioHuy.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioHuy);
        radioHuy.setText("Hủy");

        radioDangGiao.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioDangGiao);
        radioDangGiao.setText("Đang giao");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setText("Đơn Giá:");

        txtDonGia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 0, 0)));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel40.setText("SDT:");

        txtSodienThoai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 0, 0)));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel37.setText("Địa Chỉ:");

        txtDiaChi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 0, 0)));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel42.setText("Tên người nhận");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Ngày Tạo:");

        txtNgayThanhToan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 0, 0)));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Ngày Thanh toán:");

        txtNgayTao.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 0, 0)));

        trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã hủy", "Đã thanh toán", "Đang giao" }));
        trangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trangThaiActionPerformed(evt);
            }
        });

        tenSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(trangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(add)
                            .addComponent(delete)
                            .addComponent(update)
                            .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel37)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(324, 324, 324)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(txtNgayShip)
                                    .addComponent(txtSodienThoai)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(txtNgaynhan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgayTao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(txtNgayThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel41)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(radioDaThanhToan)
                                        .addGap(31, 31, 31)
                                        .addComponent(radioHuy)
                                        .addGap(41, 41, 41)
                                        .addComponent(radioDangGiao))
                                    .addComponent(tenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(txtTenNguoiNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(564, 564, 564)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(txtNgayShip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(add)
                                .addGap(41, 41, 41)
                                .addComponent(delete)
                                .addGap(53, 53, 53)
                                .addComponent(update)
                                .addGap(39, 39, 39)
                                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel20)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgaynhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(tenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtSodienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(radioDaThanhToan)
                    .addComponent(radioHuy)
                    .addComponent(radioDangGiao))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel42)
                    .addComponent(txtTenNguoiNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(301, 301, 301))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(328, 328, 328))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String maHD = txtMaHD.getText();
        String tenSP1 = String.valueOf(this.tenSP.getSelectedItem());
        String ngayTao = txtNgayTao.getText();
        String ngayTT = txtNgayThanhToan.getText();
        String ngayShip = txtNgayShip.getText();
        String ngayNhan = txtNgaynhan.getText();
        String tenNguoiNhan = txtTenNguoiNhan.getText();
        String diaChi = txtDiaChi.getText();
        String sdt = txtSodienThoai.getText();
        int soLuong = Integer.valueOf(txtSoLuong.getText());
        Double donGia1 = Double.valueOf(txtDonGia.getText());
        BigDecimal donGia = BigDecimal.valueOf(donGia1);
        Integer trangThai=0;
        if(radioHuy.isSelected()){
            trangThai=0;
        }
        else if(radioDaThanhToan.isSelected()){
            trangThai=1;
        }
        else if(radioDangGiao.isSelected()){
            trangThai=2;
        }
        //Tao moi hoa don
        HoaDon hd = new HoaDon();
        hd.setMa(maHD);
        hd.setNgayTao(ngayTao);
        hd.setNgayThanhToan(ngayTT);
        hd.setNgayShip(ngayShip);
        hd.setNgayNhan(ngayNhan);
        hd.setTrangThai(trangThai);
        hd.setTenNguoiNhan(tenNguoiNhan);
        hd.setDiaChi(diaChi);
        hd.setSdt(sdt);
        service.add(hd);
        //Tao moi hoa don ct
        hoaDonChiTiet hdct = new hoaDonChiTiet();
        hdct.setDongia(donGia);
        hdct.setSoLuong(soLuong);
        //Them hoa don
        hdct.setHoaDon(hd);
        hdct.setNgayTao(ngayTao);
        ChiTietSanPham ctsp = new ChiTietSanPham();
        int idCTSP = getIdCTSP(String.valueOf(tenSP.getSelectedItem()));
        ctsp.setId(idCTSP);
        //Them ctsp
        hdct.setChiTietSP(ctsp);
        //Them trangThai
        hdct.setTrangthai(trangThai);
        //Them hoa don chi tiet
        service.addHoaDonChiTiet(hdct);
        listHoaDon = service.getAllHoaDon();
        int id = hd.getId();
        HoaDonCustom2 hdcustom2 = new HoaDonCustom2(id, maHD, tenSP1, ngayTao, ngayNhan, ngayShip, ngayNhan, tenNguoiNhan, diaChi, sdt, soLuong, donGia, trangThai);
        
        if(radioHuy.isSelected()){
            listHoaDonHuy.add(hdcustom2);
        }
        else if(radioDaThanhToan.isSelected()){
            listHoaDonThanhToan.add(hdcustom2);
        }
        else if(radioDangGiao.isSelected()){
            listHoaDonGiao.add(hdcustom2);
        }
        duyetTinhTrang(listHoaDon);
        loadTinhTrang();
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        int index = table.getSelectedRow();
        int tinhTrang=0;
        if(radioHuy.isSelected()){
            tinhTrang=0;
        }
        else if(radioDaThanhToan.isSelected()){
            tinhTrang=1;
        }
        else if(radioDangGiao.isSelected()){
            tinhTrang=2;
        }
        String maHD = txtMaHD.getText();
        String tenSP1 = String.valueOf(this.tenSP.getSelectedItem());
        String ngayTao = txtNgayTao.getText();
        String ngayTT = txtNgayThanhToan.getText();
        String ngayShip = txtNgayShip.getText();
        String ngayNhan = txtNgaynhan.getText();
        String tenNguoiNhan = txtTenNguoiNhan.getText();
        String diaChi = txtDiaChi.getText();
        String sdt = txtSodienThoai.getText();
        int soLuong = Integer.valueOf(txtSoLuong.getText());
        Double donGia1 = Double.valueOf(txtDonGia.getText());
        BigDecimal donGia = BigDecimal.valueOf(donGia1);
        // khai bao hoa don custom2
        HoaDonCustom2 hdc2 = new HoaDonCustom2();
        if(trangThai.getSelectedIndex()==0){
            hdc2 = listHoaDonHuy.get(index);
        }
        else if(trangThai.getSelectedIndex()==1){
            hdc2 = listHoaDonThanhToan.get(index);
        }
        else if(trangThai.getSelectedIndex()==2 ){
            hdc2 = listHoaDonGiao.get(index);
        }
        //khai bao hd
        HoaDon hd = new HoaDon();
        hd.setMa(hdc2.getMa());
        hd.setNgayTao(hdc2.getNgayTao());
        hd.setNgayThanhToan(hdc2.getNgayThanhToan());
        hd.setNgayShip(hdc2.getNgayShip());
        hd.setNgayNhan(hdc2.getNgayNhan());
        hd.setTrangThai(hdc2.getTrangThai());
        hd.setTenNguoiNhan(hdc2.getTenNguoiNhan());
        hd.setDiaChi(hdc2.getDiaChi());
        hd.setSdt(hdc2.getSdt());
        hd.setId(hdc2.getId());
        hoaDonChiTiet hdct = new hoaDonChiTiet();
        hdct.setDongia(donGia);
        hdct.setSoLuong(soLuong);
        //Them hoa don
        hdct.setHoaDon(hd);
        hdct.setNgayTao(ngayTao);
        ChiTietSanPham ctsp = new ChiTietSanPham();
        int idCTSP = getIdCTSP(String.valueOf(tenSP.getSelectedItem()));
        ctsp.setId(idCTSP);
        //Them ctsp
        hdct.setChiTietSP(ctsp);
        //Them trangThai
        hdct.setTrangthai(trangThai.getSelectedIndex());
        JOptionPane.showMessageDialog(rootPane, service.updateHoaDonCT(hdct, hd, hdc2.getId(), idCTSP, ngayTao, ngayTT, ngayShip, ngayNhan, tenNguoiNhan, soLuong, tinhTrang ,donGia, sdt, diaChi));
//hoaDonChiTiet hdct,HoaDon hd, int id,
//            int idCtSP, String ngayTao, String ngayNhan, String ngayShip, String ngayThanhToan,
//            String tenNguoiNhan, int soLuong, int tinhTrang, BigDecimal donGia, String sdt, String diaChi)
        listHoaDon=service.getAllHoaDon();
        if(tinhTrang==0&&trangThai.getSelectedIndex()!=0){
            listHoaDonHuy.add(hdc2);
        }
        if(tinhTrang==1&&trangThai.getSelectedIndex()!=1){
            listHoaDonThanhToan.add(hdc2);
        }
        if(tinhTrang==2&&trangThai.getSelectedIndex()!=2){
            listHoaDonGiao.add(hdc2);
        }
        loadTinhTrang();
    }//GEN-LAST:event_updateActionPerformed

    private void trangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trangThaiActionPerformed
        if(trangThai.getSelectedIndex()==0){
            loadTable(listHoaDonHuy);
        }
        else if(trangThai.getSelectedIndex()==1){
            loadTable(listHoaDonThanhToan);
        }
        else if(trangThai.getSelectedIndex()==2){
            loadTable(listHoaDonGiao);
        }
    }//GEN-LAST:event_trangThaiActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int index = table.getSelectedRow();
        HoaDonCustom2 hdc2 = new HoaDonCustom2();
        if(trangThai.getSelectedIndex()==0){
            hdc2 = listHoaDonHuy.get(index);
            radioHuy.setSelected(true);
        }
        else if(trangThai.getSelectedIndex()==1){
            hdc2 = listHoaDonThanhToan.get(index);
            radioDaThanhToan.setSelected(true);
        }
        else if(trangThai.getSelectedIndex()==2 ){
            hdc2 = listHoaDonGiao.get(index);
            radioDangGiao.setSelected(true);
        }
        txtDiaChi.setText(hdc2.getDiaChi());
        txtDonGia.setText(String.valueOf(hdc2.getDongia()));
        txtMaHD.setText(hdc2.getMa());
        txtNgayShip.setText(hdc2.getNgayShip());
        txtNgayTao.setText(hdc2.getNgayTao());
        txtNgayThanhToan.setText(hdc2.getNgayThanhToan());
        txtNgaynhan.setText(hdc2.getNgayNhan());
        txtSoLuong.setText(String.valueOf(hdc2.getSoLuong()));
        txtSodienThoai.setText(hdc2.getSdt());
        txtTenNguoiNhan.setText(hdc2.getTenNguoiNhan());
        tenSP.setSelectedItem(hdc2.getTenSP());
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonQuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonQuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonQuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonQuanLyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonQuanLyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField check;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioDaThanhToan;
    private javax.swing.JRadioButton radioDangGiao;
    private javax.swing.JRadioButton radioHuy;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> tenSP;
    private javax.swing.JComboBox<String> trangThai;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtNgayShip;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtNgayThanhToan;
    private javax.swing.JTextField txtNgaynhan;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSodienThoai;
    private javax.swing.JTextField txtTenNguoiNhan;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
