/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Util.MoneyUtil;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.IThongKeSevice;
import service.impl.ThongKeSeviceImpl;
import viewmodel.ThongKeCustom;

/**
 *
 * @author asus_vinh
 */
public class ThongKeForm extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    DefaultComboBoxModel dcbmThang = new DefaultComboBoxModel();
    DefaultComboBoxModel dcbmNam = new DefaultComboBoxModel();
    List<ThongKeCustom> listThongKe = new ArrayList<>();
    DefaultComboBoxModel dcbmNam1 = new DefaultComboBoxModel();
    List<String> listnam = new ArrayList<>();
    private ThongKeSeviceImpl thongKeSevice = new ThongKeSeviceImpl();

    /**
     * Creates new form ThongKeForm
     */
    public ThongKeForm() {
        initComponents();
        tbThongKe.setModel(dtm);
        String[] hedear = {"Sản phẩm", "Số lượng", "Giá cao nhất", "Giá thấp nhất", "Doanh thu"};
        dtm.setColumnIdentifiers(hedear);
        listLoad();
        cbbThang();
        cbbNam();
        cbbNam1();
        loadThongKe();
        anCBB();
    }

    private void anCBB() {
        cbbNam.setVisible(false);
        cbbThang.setVisible(false);

    }

    private void hienCbbThang() {
        cbbThang.setVisible(true);

    }

    private void anCbbThang() {
        cbbThang.setVisible(false);

    }

    private void anCbbNam() {
        cbbNam.setVisible(false);

    }

    private void hienCbbNam() {
        cbbNam.setVisible(true);

    }

    private void listLoad() {
        listThongKe = new ThongKeSeviceImpl().getAll();
        showDataRow(listThongKe);
    }

    private void listSearh(String ten) {
        listThongKe = new ThongKeSeviceImpl().searh(ten);
        showDataRow(listThongKe);
    }

    private void showDataRow(List<ThongKeCustom> listS) {
        dtm.setRowCount(0);
        for (ThongKeCustom p : listS) {
            dtm.addRow(p.toDataRow());
        }
    }

    private void cbbThang() {
        cbbThang.setModel(dcbmThang);
        for (int i = 01; i <= 12; i++) {
            if (i < 10) {
                dcbmThang.addElement("0" + i);
            } else {
                dcbmThang.addElement(i);
            }
        }

    }

    private void cbbNam() {
        cbbNam.setModel(dcbmNam);
        for (int i = 2020; i <= 2023; i++) {
            dcbmNam.addElement(i);
        }
    }

    private void cbbNam1() {
        cboNam1.setModel(dcbmNam1);
        for (int i = 2020; i <= 2023; i++) {
            listnam.add(String.valueOf(i));
        }
        dcbmNam1.addAll(listnam);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbDoanhThu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbSoHoaDon = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbSoHangHuy = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbSoSPBanDuoc = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbThongKe = new javax.swing.JTable();
        cboNam1 = new javax.swing.JComboBox<>();
        txtTimKiem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        radioTatCa = new javax.swing.JRadioButton();
        radioThang = new javax.swing.JRadioButton();
        radioNam = new javax.swing.JRadioButton();
        cbbThang = new javax.swing.JComboBox<>();
        cbbNam = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Doanh Thu");

        lbDoanhThu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbDoanhThu.setText("jLabel6");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("VNĐ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(lbDoanhThu)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel8)
                        .addGap(31, 31, 31))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDoanhThu)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Số hóa đơn");

        lbSoHoaDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSoHoaDon.setText("jLabel7");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lbSoHoaDon)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(lbSoHoaDon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Số hàng hủy");

        lbSoHangHuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSoHangHuy.setText("jLabel8");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lbSoHangHuy)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(lbSoHangHuy)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Số sản phẩm bán được");

        lbSoSPBanDuoc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSoSPBanDuoc.setText("jLabel9");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lbSoSPBanDuoc)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addComponent(lbSoSPBanDuoc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tbThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sản Phẩm", "số Lượng", "giá cao nhất", "giá thấp nhất", "doanh thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tbThongKe);

        cboNam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNam1ActionPerformed(evt);
            }
        });

        txtTimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemCaretUpdate(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Tìm kiếm sản phẩm:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Năm: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboNam1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboNam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroup1.add(radioTatCa);
        radioTatCa.setSelected(true);
        radioTatCa.setText("Tất cả");
        radioTatCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioTatCaMouseClicked(evt);
            }
        });

        buttonGroup1.add(radioThang);
        radioThang.setText("Theo tháng");
        radioThang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioThangMouseClicked(evt);
            }
        });

        buttonGroup1.add(radioNam);
        radioNam.setText("Theo năm");
        radioNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioNamMouseClicked(evt);
            }
        });

        cbbThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbThangActionPerformed(evt);
            }
        });

        cbbNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(radioTatCa)
                .addGap(29, 29, 29)
                .addComponent(radioThang)
                .addGap(35, 35, 35)
                .addComponent(radioNam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTatCa)
                    .addComponent(radioThang)
                    .addComponent(radioNam)
                    .addComponent(cbbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radioTatCaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioTatCaMouseClicked
        loadThongKe();
        anCBB();
    }//GEN-LAST:event_radioTatCaMouseClicked

    private void loadThongKe() {
        BigDecimal doanhThuTong = thongKeSevice.doanhThu();
        Long soHoaDon = thongKeSevice.soHoaDon();
        Long soHoaDonHuy = thongKeSevice.soHoaDonHuy(-1);
        Long soSanPhamBanDuoc = thongKeSevice.soSanPhamBanDuoc();

        lbDoanhThu.setText(String.valueOf(MoneyUtil.formatMoney(String.valueOf(doanhThuTong))));
        lbSoHoaDon.setText(String.valueOf(soHoaDon));
        lbSoHangHuy.setText(String.valueOf(soHoaDonHuy));
        lbSoSPBanDuoc.setText(String.valueOf(soSanPhamBanDuoc));
    }

    private void txtTimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemCaretUpdate
        if (txtTimKiem.getText().trim().length() > 0) {
            listSearh(txtTimKiem.getText());
        } else {
            listLoad();
        }

    }//GEN-LAST:event_txtTimKiemCaretUpdate

    private void cboNam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNam1ActionPerformed

        listSearhNam(String.valueOf(cboNam1.getSelectedItem()));

    }//GEN-LAST:event_cboNam1ActionPerformed

    private void radioThangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioThangMouseClicked
        loadThongKeTheoThang();  //String.valueOf(cbbThang.getSelectedItem())
        hienCbbThang();
        anCbbNam();
    }//GEN-LAST:event_radioThangMouseClicked

    private void loadThongKeTheoThang() {
        BigDecimal doanhThuTheoTungThang = thongKeSevice.doanhThuTheoTungThang();
        Long soHoaDonTheoThang = thongKeSevice.soHoaDonTheoThang(String.valueOf(cbbThang.getSelectedItem()));
        Long soHoaDonHuyTheoThang = thongKeSevice.soHoaDonHuyTheoThang(-1, String.valueOf(cbbThang.getSelectedItem()));
        Long soSanPhamBanDuocTheoThang = thongKeSevice.soSanPhamBanDuocTheoThang(String.valueOf(cbbThang.getSelectedItem()));

        lbDoanhThu.setText(String.valueOf(MoneyUtil.formatMoney(String.valueOf(doanhThuTheoTungThang))));
        lbSoHoaDon.setText(String.valueOf(soHoaDonTheoThang));
        lbSoHangHuy.setText(String.valueOf(soHoaDonHuyTheoThang));
        lbSoSPBanDuoc.setText(String.valueOf(soSanPhamBanDuocTheoThang));
    }

    private void radioNamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioNamMouseClicked

        loadThongKeTheoNam();
        hienCbbNam();
        anCbbThang();
    }//GEN-LAST:event_radioNamMouseClicked

    private void cbbThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbThangActionPerformed
        //    System.out.println(String.valueOf(cbbThang.getSelectedItem()));
        loadThongKeTheoCbbThang(String.valueOf(cbbThang.getSelectedItem()));

    }//GEN-LAST:event_cbbThangActionPerformed

    private void cbbNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNamActionPerformed
        loadThongKeTheoCbbNam(String.valueOf(cbbNam.getSelectedItem()));
    }//GEN-LAST:event_cbbNamActionPerformed

    private void loadThongKeTheoCbbThang(String thang) {
        BigDecimal doanhThuTheoTungThangCBB = thongKeSevice.doanhThuTheoTungThangCBB(thang);
        Long soHoaDonTheoThang = thongKeSevice.soHoaDonTheoThang(thang);
        Long soHoaDonHuyTheoThang = thongKeSevice.soHoaDonHuyTheoThang(-1, thang);
        Long soSanPhamBanDuocTheoThang = thongKeSevice.soSanPhamBanDuocTheoThang(thang);
        if (doanhThuTheoTungThangCBB == null) {
            lbDoanhThu.setText("0");
            lbSoHoaDon.setText("0");
            lbSoHangHuy.setText("0");
            lbSoSPBanDuoc.setText("0");
        } else {
            lbDoanhThu.setText(String.valueOf(MoneyUtil.formatMoney(String.valueOf(doanhThuTheoTungThangCBB))));
            lbSoHoaDon.setText(String.valueOf(soHoaDonTheoThang));
            lbSoHangHuy.setText(String.valueOf(soHoaDonHuyTheoThang));
            lbSoSPBanDuoc.setText(String.valueOf(soSanPhamBanDuocTheoThang));
        }

    }

    private void loadThongKeTheoCbbNam(String thang) {
        BigDecimal doanhThuTheoTungNamCBB = thongKeSevice.doanhThuTheoTungNamCBB(thang);
        Long soHoaDonTheoNam = thongKeSevice.soHoaDonTheoNam(thang);
        Long soHoaDonHuyTheoNam = thongKeSevice.soHoaDonHuyTheoNam(-1, thang);
        Long soSanPhamBanDuocTheoNam = thongKeSevice.soSanPhamBanDuocTheoNam(thang);
        if (doanhThuTheoTungNamCBB == null) {
            lbDoanhThu.setText("0");
            lbSoHoaDon.setText("0");
            lbSoHangHuy.setText("0");
            lbSoSPBanDuoc.setText("0");
        } else {
            lbDoanhThu.setText(String.valueOf(MoneyUtil.formatMoney(String.valueOf(doanhThuTheoTungNamCBB))));
            lbSoHoaDon.setText(String.valueOf(soHoaDonTheoNam));
            lbSoHangHuy.setText(String.valueOf(soHoaDonHuyTheoNam));
            lbSoSPBanDuoc.setText(String.valueOf(soSanPhamBanDuocTheoNam));
        }

    }

    private void loadThongKeTheoNam() {
        BigDecimal doanhThuTheoNam = thongKeSevice.doanhThuTheoNam();
        Long soHoaDonTheoNam = thongKeSevice.soHoaDonTheoNamN();
        Long soHoaDonHuyTheoNam = thongKeSevice.soHoaDonHuyTheoNam(-1, String.valueOf(cbbNam.getSelectedItem()));
        Long soSanPhamBanDuocTheoNam = thongKeSevice.soSanPhamBanDuocTheoNamN();

        lbDoanhThu.setText(String.valueOf(MoneyUtil.formatMoney(String.valueOf(doanhThuTheoNam))));
        lbSoHoaDon.setText(String.valueOf(soHoaDonTheoNam));
        lbSoHangHuy.setText(String.valueOf(soHoaDonHuyTheoNam));
        lbSoSPBanDuoc.setText(String.valueOf(soSanPhamBanDuocTheoNam));
    }

    private void listSearhNam(String ten) {
        listThongKe = new ThongKeSeviceImpl().searhNam(ten);
        showDataRow(listThongKe);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbNam;
    private javax.swing.JComboBox<String> cbbThang;
    private javax.swing.JComboBox<String> cboNam1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbDoanhThu;
    private javax.swing.JLabel lbSoHangHuy;
    private javax.swing.JLabel lbSoHoaDon;
    private javax.swing.JLabel lbSoSPBanDuoc;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioTatCa;
    private javax.swing.JRadioButton radioThang;
    private javax.swing.JTable tbThongKe;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

}
